services:
  - type: web
    name: job-posting-app
    env: node
    buildCommand: npm run build && npm install --prefix backend
    startCommand: npm run start:server
    envVars:
      - key: MONGODB_USER
        sync: false
      - key: MONGODB_PASSWORD
        sync: false
      - key: MONGODB_CLUSTER
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: /api

